@php
    $inv = $invoice;
    $customer = $inv->customer;
    $items = $inv->items ?? collect();
@endphp
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Invoice #{{ $inv->id }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        @page {
            margin: 24px;
        }

        body {
            font-family: DejaVu Sans, Arial, Helvetica, sans-serif;
            color: #111;
            font-size: 12px;
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-bottom: 16px;
        }

        .brand {
            font-weight: 700;
            font-size: 18px;
        }

        .muted {
            color: #555;
        }

        .box {
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 12px;
            margin-top: 8px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            padding: 8px;
        }

        thead th {
            background: #f3f4f6;
            text-align: left;
            border-bottom: 1px solid #e5e7eb;
        }

        tbody td {
            border-bottom: 1px solid #f1f5f9;
        }

        tfoot td {
            border-top: 1px solid #e5e7eb;
            font-weight: 700;
        }

        .right {
            text-align: right;
        }

        .tiny {
            font-size: 10px;
            color: #666;
        }
    </style>
</head>

<body>
    <div class="header">
        <div>
            <div class="brand">Single Inventory</div>
            <div class="muted tiny">single-store billing system</div>
        </div>
        <div class="right">
            <div><strong>Invoice #:</strong> {{ $inv->id }}</div>
            <div class="muted">Date: {{ \Carbon\Carbon::parse($inv->created_at)->format('d M Y, h:i A') }}</div>
        </div>
    </div>

    <div class="box">
        <strong>Bill To:</strong><br>
        {{ $customer?->name }}<br>
        @if ($customer?->email)
            <span class="muted">{{ $customer->email }}</span><br>
        @endif
        @if ($customer?->phone)
            <span class="muted">{{ $customer->phone }}</span><br>
        @endif
        @if ($customer?->address)
            <span class="muted">{{ $customer->address }}</span>
        @endif
    </div>

    <div style="height:10px"></div>

    <table>
        <thead>
            <tr>
                <th style="width:42%">Product</th>
                <th>SKU</th>
                <th class="right">Price</th>
                <th class="right">Qty</th>
                <th class="right">Subtotal</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($items as $it)
                <tr>
                    <td>{{ $it->product?->name }}</td>
                    <td class="muted">{{ $it->product?->sku }}</td>
                    <td class="right">BDT {{ ($it->price) }}</td>
                    <td class="right">{{ $it->quantity }}</td>
                    <td class="right">BDT {{($it->subtotal ?? $it->price * $it->quantity) }}</td>
                </tr>
            @endforeach
            @if ($items->count() === 0)
                <tr>
                    <td colspan="5" class="muted">No items.</td>
                </tr>
            @endif
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" class="right">Total</td>
                <td class="right">BDT {{ ($inv->total) }}</td>
            </tr>
        </tfoot>
    </table>

    <div style="height:16px"></div>
    <div class="tiny">Generated by Single Inventory • {{ now()->format('d M Y, h:i A') }}</div>
</body>

</html>
